#!/bin/bash

# Hafif ortamlarda kurulum yapma.
anyattr base && skiptask "baz sistem"

sudoattempt

# bir nedenle sistemde bulunan alternatif artıklarını elle sil
for p in ruby gem ri erb testrb rdoc; do
	say "$p sistem alternatifleri (varsa) silinecek..."
	sudo update-alternatives --remove-all $p >/dev/null 2>&1 ||:
done

if [ -z "$HAS_APT_UPDATED" ]; then
	say "Paket indeksleri güncelleniyor..."
	xaptget update ||:
fi

# kaba kuvvete dayalı bir çözüm olarak Ruby paketlerini tekrar kur.  Dikkat!
# ruby1.8 için rake ve gem'i kurmuyoruz.
xaptget install --reinstall ruby1.9.1 ruby1.9.1-dev ri1.9.1 ruby1.8 ruby1.8-dev ri1.8 build-essential

# Yeni sürümlerde kullanılan alternatif sistemini eski sistemlere birebir uyarla.
RUBY_VERSION=$(dpkg-query -W -f='${Version}' ruby1.9.1 2>/dev/null ||:)
if dpkg --compare-versions "${RUBY_VERSION}" lt 1.9.2.180-2; then
	p=10; for v in "1.9.1" "1.8"; do
		say "Ruby ${v} sistem alternatifleri kuruluyor..."
		# ruby
		sudo update-alternatives --install /usr/bin/ruby ruby /usr/bin/ruby${v} $p \
			--slave   /usr/share/man/man1/ruby.1.gz ruby.1.gz \
						/usr/share/man/man1/ruby${v}.1.gz \
			--slave   /usr/share/man/man1/erb.1.gz erb.1.gz \
						/usr/share/man/man1/erb${v}.1.gz \
			--slave   /usr/share/man/man1/irb.1.gz irb.1.gz \
						/usr/share/man/man1/irb${v}.1.gz \
			--slave   /usr/share/man/man1/ri.1.gz ri.1.gz \
						/usr/share/man/man1/ri${v}.1.gz \
			--slave   /usr/share/man/man1/rdoc.1.gz rdoc.1.gz \
						/usr/share/man/man1/rdoc${v}.1.gz \
			--slave   /usr/share/man/man1/testrb.1.gz testrb.1.gz \
						/usr/share/man/man1/testrb${v}.1.gz \
			--slave   /usr/bin/erb erb /usr/bin/erb${v} \
			--slave   /usr/bin/irb irb /usr/bin/irb${v} \
			--slave   /usr/bin/rdoc rdoc /usr/bin/rdoc${v} \
			--slave   /usr/bin/ri ri /usr/bin/ri${v} \
			--slave   /usr/bin/testrb testrb /usr/bin/testrb${v} ||: # hatasız
		# gem
		sudo update-alternatives --install /usr/bin/gem gem /usr/bin/gem${v} $p \
			--slave   /usr/share/man/man1/gem.1.gz gem.1.gz \
						/usr/share/man/man1/gem${v}.1.gz \
			--slave /etc/bash_completion.d/gem bash_completion_gem \
						/etc/bash_completion.d/gem${v} ||: # hatasız
		# 1.9.1 → 10 ve 1.8 → 50 önceliğinde (öntanımlı ruby1.8)
		p+=40
	done >/dev/null 2>&1 # sessiz
fi

# Resmi alternatiflerde ruby1.8 öntanımlı.  Bunu 1.9.1 yap.
say "Öntanımlı Ruby sürümü 1.9.1 olarak ayarlanıyor..."
sudo update-alternatives --set ruby /usr/bin/ruby1.9.1
sudo update-alternatives --set gem /usr/bin/gem1.9.1
