#!/bin/bash

use std

PROGNAME=${0##*/}

ensuredeb wwwconfig-common

dbadmin=${WWWCONFIG_COMMON_DBADMIN:-root}

while :; do
	asksecret "Mysql yönetici (root) parolası"
	dbadmpass="$REPLY"

	ask "Veritabanı ismi (Örnek: 'moodle', 'wp')" "" must-non-empty
	dbname="$REPLY"

	ask "Veritabanı kullanıcısı (Veritabanı ismi ile aynı olması önerilir)" "$dbname" must-non-empty
	dbuser="$REPLY"

	asksecret "'$dbuser' veritabanı kullanıcı için parola" ""

	cry "\nBu girdilerle devam edilecek:\n\n\tVeritabanı: $dbname\n\tKullanıcı: $dbuser\n"
	if yesno "Onaylıyor musunuz?" e; then
		export dbadmin dbadmpass dbname dbuser
		break
	fi
done

(
	. /usr/share/wwwconfig-common/mysql-createuser.sh
	if [ "$status" = "error" ]; then
		echo >&2 "$error"
		exit 1
	fi
) || die "'$dbuser' isimli veritabanı kullanıcısı oluşturulamadı."

case "$PROGNAME" in
*kullanıcı* | *kullanici* | *user*) exit 0;;
esac

(
	. /usr/share/wwwconfig-common/mysql-createdb.sh
	if [ "$status" = "error" ]; then
		echo >&2 "$error"
		exit 1
	fi
) || die "'$dbname' isimli veritabanı oluşturulamadı."
