#!/bin/bash

set -e

[ -z "$X" ] || cd "$X"

origin_url="$(git config remote.origin.url 2>/dev/null ||:)"
upstream_url="$(git config remote.upstream.url 2>/dev/null ||:)"
update_cmd="git pull"; hascommand gx-update && update_cmd=gx-update

say "Depo güncelleniyor..."
printf "\tUzak depo\t$origin_url\n\tÜst depo\t$upstream_url\n"

say "Yerel depo uzak depo ile eşzamanlanıyor..."
prev=$(git show --format='format:%H' HEAD 2>/dev/null ||:)
$update_cmd origin master
case "$(git show --format='format:%H' HEAD 2>/dev/null ||:)" in
$prev)
	cry "Değişiklik yok."
	;;
*)
	cry "Uzak depodaki değişiklikler alındı."
	;;
esac

case "$origin_url" in
git@*|https://*@*)
	say "Üst depo değişiklikleri alınıyor..."
	prev=$(git show --format='format:%H' HEAD 2>/dev/null ||:)
	$update_cmd upstream master
	case "$(git show --format='format:%H' HEAD 2>/dev/null ||:)" in
	$prev)
		cry "Değişiklik yok."
		;;
	*)
		cry "Üst depodan alınan değişiklikler uzak depoya gönderiliyor..."
		git push --all
		;;
	esac
	;;
*)
	cry "Bu bir salt okunur çalışma kopyası olduğundan üst" \
	    "depo değişiklikleri alınmayacak."
	;;
esac
