#!/bin/bash

set -e

[ -z "$X" ] || cd "$X"

origin_url="$(git config remote.origin.url 2>/dev/null ||:)"
upstream_url="$(git config remote.upstream.url 2>/dev/null ||:)"

say "Depo güncelleniyor..."
say "\tUzak depo\t$origin_url"
say "\tÜst depo\t$upstream_url"
say ""

say "Yerel depo uzak depo ile eşzamanlanıyor..."
prev=$(git show --format='format:%H' HEAD 2>/dev/null ||:)
git pull origin master
case "$(git show --format='format:%H' HEAD 2>/dev/null ||:)" in
$prev)
	cry "Değişiklik yok."
	;;
*)
	cry "Uzak depodaki değişiklikler alındı."
	;;
esac

case "$origin_url" in
git://git@*|https://*@*)
	say "Üst depo değişiklikleri alınıyor..."
	prev=$(git show --format='format:%H' HEAD 2>/dev/null ||:)
	git pull upstream master
	case "$(git show --format='format:%H' HEAD 2>/dev/null ||:)" in
	$prev)
		cry "Değişiklik yok."
		;;
	*)
		cry "Üst depodan alınan değişiklikler uzak depoya gönderiliyor..."
		git push --all
		;;
	esac
	;;
*)
	cry "Bu bir salt okunur çalışma kopyası olduğundan üst" \
	    "depo değişiklikleri alınmayacak."
	;;
esac
